// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOETCJsopcjbiIyBKzu22zewVVOGZKNk8',
    appId: '1:1069058523554:web:25a023c0288bd632f7b2fb',
    messagingSenderId: '1069058523554',
    projectId: 'anomalyreport-4163e',
    authDomain: 'anomalyreport-4163e.firebaseapp.com',
    databaseURL: 'https://anomalyreport-4163e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'anomalyreport-4163e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzhKr8lhlpKHB0TCGtxmqllEtWnq_c2xo',
    appId: '1:1069058523554:android:ba00ad614f00d588f7b2fb',
    messagingSenderId: '1069058523554',
    projectId: 'anomalyreport-4163e',
    databaseURL: 'https://anomalyreport-4163e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'anomalyreport-4163e.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkcsCsRadbQUgzihdTxYzipkuSgDz0o5s',
    appId: '1:1069058523554:ios:8568e56fe203bb9ff7b2fb',
    messagingSenderId: '1069058523554',
    projectId: 'anomalyreport-4163e',
    databaseURL: 'https://anomalyreport-4163e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'anomalyreport-4163e.appspot.com',
    iosClientId: '1069058523554-a8fek20bd1r47fvmvfpnq8aoomhers1b.apps.googleusercontent.com',
    iosBundleId: 'com.diy.anomalyreport',
  );
}
